# Default values for infrapulse.

replicaCount: 1

image:
  repository: infrapulse-web
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

redis:
  enabled: true
  image: redis:7.0-alpine
  port: 6379

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

probes:
  liveness:
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 10
  readiness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10

securityContext:
  runAsUser: 10001
  runAsGroup: 10001
  runAsNonRoot: true
