apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubemonitor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Kuriy35/kubemonitor.git'
    targetRevision: HEAD
    path: helm/kubemonitor
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kubemonitor
  syncPolicy:
    automated:
      prune: true  
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
